global:
   scrape_interval: 5s
   external_labels:
       monitor: 'demo-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prom.free5gc.org']
  - job_name: 'api_monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['amf.free5gc.org:3000']